## Lesson 12: Numpy

In [1]:
import numpy as np 

In [2]:
arr1 = np.array([1,2,3])
arr1 

array([1, 2, 3])

In [3]:
arr2 = np.array([1,2.1,3])
arr2  

array([1. , 2.1, 3. ])

In [4]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.ones(shape= (3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.full(shape=(3,5), fill_value = 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [9]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [10]:
np.random.seed(0)
arr = np.random.randint(1,10, (3,4))
arr 

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]], dtype=int32)

In [11]:
arr.ndim

2

In [12]:
arr.shape 

(3, 4)

In [13]:
arr.size 

12

In [14]:
arr.dtype

dtype('int32')

In [15]:
np.random.seed(0)
arr = np.random.randint(1,10, (3,4))
arr_1 = np.random.randint(1,10, (3,4), dtype = 'int8')

In [16]:
arr 

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]], dtype=int32)

In [17]:
arr_1

array([[9, 3, 7, 6],
       [3, 2, 3, 9],
       [7, 8, 8, 9]], dtype=int8)

In [18]:
arr.nbytes

48

In [19]:
arr_1.nbytes

12

In [20]:
arr.itemsize

4

In [21]:
arr1 

array([1, 2, 3])

In [22]:
arr1[0]

np.int64(1)

In [23]:
arr1[1] = 3.14
arr1 

array([1, 3, 3])

In [24]:
arr1[1] = 4
arr1 

array([1, 4, 3])

In [25]:
arr1[1] = '3'
arr1 

array([1, 3, 3])

In [26]:
np.array([1,2,'1', 3.14])

array(['1', '2', '1', '3.14'], dtype='<U32')

In [27]:
arr1[:2]

array([1, 3])

In [28]:
arr1[-1]

np.int64(3)

In [29]:
arr 

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]], dtype=int32)

In [30]:
arr[1,2]

np.int32(6)

In [31]:
arr[0,:]

array([6, 1, 4, 4], dtype=int32)

In [32]:
arr[:,1]

array([1, 4, 8], dtype=int32)

In [33]:
np.random.seed(0)
x3 = np.random.randint(1,20, (3,4,6))
x3 

array([[[13, 16,  1,  4,  4,  8],
        [10, 19,  5,  7, 13,  2],
        [ 7,  8, 15, 18,  6, 14],
        [ 9, 10, 17,  6, 16, 16]],

       [[ 1, 19,  4, 18, 15,  8],
        [ 1,  2, 10,  1, 11,  4],
        [12, 19,  3,  1,  1,  5],
        [ 6,  7,  9, 18, 16,  5]],

       [[10, 11,  2,  2,  8, 10],
        [ 4,  7, 12, 15, 19,  1],
        [15,  4, 13, 11, 12,  5],
        [ 7,  5, 16,  4, 13,  5]]], dtype=int32)

In [34]:
x3[0,:,:]

array([[13, 16,  1,  4,  4,  8],
       [10, 19,  5,  7, 13,  2],
       [ 7,  8, 15, 18,  6, 14],
       [ 9, 10, 17,  6, 16, 16]], dtype=int32)

In [35]:
arr 

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]], dtype=int32)

In [36]:
sub_arr = arr[1:,1:3]
sub_arr

array([[4, 6],
       [8, 7]], dtype=int32)

In [37]:
sub_arr[0,0] = 99999
sub_arr

array([[99999,     6],
       [    8,     7]], dtype=int32)

In [38]:
arr 

array([[    6,     1,     4,     4],
       [    8, 99999,     6,     3],
       [    5,     8,     7,     9]], dtype=int32)

In [40]:
A = np.random.randint(1,10, (4,5))
A 

array([[5, 9, 5, 4, 8],
       [6, 6, 1, 2, 6],
       [4, 1, 6, 1, 2],
       [3, 5, 3, 1, 4]], dtype=int32)

In [43]:
np.delete(A, obj= [1,2], axis = 1)

array([[5, 4, 8],
       [6, 2, 6],
       [4, 1, 2],
       [3, 1, 4]], dtype=int32)

In [44]:
np.delete(A, obj= [1,2], axis = 0)

array([[5, 9, 5, 4, 8],
       [3, 5, 3, 1, 4]], dtype=int32)

In [45]:
A 

array([[5, 9, 5, 4, 8],
       [6, 6, 1, 2, 6],
       [4, 1, 6, 1, 2],
       [3, 5, 3, 1, 4]], dtype=int32)

In [46]:
A.reshape(2,10)

array([[5, 9, 5, 4, 8, 6, 6, 1, 2, 6],
       [4, 1, 6, 1, 2, 3, 5, 3, 1, 4]], dtype=int32)

In [49]:
A.reshape(2,2,-1)

array([[[5, 9, 5, 4, 8],
        [6, 6, 1, 2, 6]],

       [[4, 1, 6, 1, 2],
        [3, 5, 3, 1, 4]]], dtype=int32)

In [48]:
np.delete(A.reshape(2,2,-1), obj=0, axis=0)

array([[[4, 1, 6, 1, 2],
        [3, 5, 3, 1, 4]]], dtype=int32)

In [50]:
np.delete(A.reshape(2,2,-1), obj=0, axis=1)

array([[[6, 6, 1, 2, 6]],

       [[3, 5, 3, 1, 4]]], dtype=int32)

In [51]:
np.delete(A.reshape(2,2,-1), obj=0, axis=2)

array([[[9, 5, 4, 8],
        [6, 1, 2, 6]],

       [[1, 6, 1, 2],
        [5, 3, 1, 4]]], dtype=int32)

In [53]:
A 

array([[5, 9, 5, 4, 8],
       [6, 6, 1, 2, 6],
       [4, 1, 6, 1, 2],
       [3, 5, 3, 1, 4]], dtype=int32)

In [52]:
A.flatten()

array([5, 9, 5, 4, 8, 6, 6, 1, 2, 6, 4, 1, 6, 1, 2, 3, 5, 3, 1, 4],
      dtype=int32)

In [54]:
B = np.arange(20).reshape(4,-1)
B 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
np.concatenate([A,B], axis = 1)

array([[ 5,  9,  5,  4,  8,  0,  1,  2,  3,  4],
       [ 6,  6,  1,  2,  6,  5,  6,  7,  8,  9],
       [ 4,  1,  6,  1,  2, 10, 11, 12, 13, 14],
       [ 3,  5,  3,  1,  4, 15, 16, 17, 18, 19]])

In [58]:
np.concatenate([A,B], axis = 0)

array([[ 5,  9,  5,  4,  8],
       [ 6,  6,  1,  2,  6],
       [ 4,  1,  6,  1,  2],
       [ 3,  5,  3,  1,  4],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.vstack((A,B)) # np.concat with axis = 0

array([[ 5,  9,  5,  4,  8],
       [ 6,  6,  1,  2,  6],
       [ 4,  1,  6,  1,  2],
       [ 3,  5,  3,  1,  4],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
np.hstack((A,B)) # np.concat with axis  = 1

array([[ 5,  9,  5,  4,  8,  0,  1,  2,  3,  4],
       [ 6,  6,  1,  2,  6,  5,  6,  7,  8,  9],
       [ 4,  1,  6,  1,  2, 10, 11, 12, 13, 14],
       [ 3,  5,  3,  1,  4, 15, 16, 17, 18, 19]])

In [66]:
X = np.arange(1,13)
X 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
np.split(X, 2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [68]:
np.split(X, 3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [69]:
np.split(X, 4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [70]:
np.split(X, [3, 5, 8])

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8]), array([ 9, 10, 11, 12])]

In [71]:
A 

array([[5, 9, 5, 4, 8],
       [6, 6, 1, 2, 6],
       [4, 1, 6, 1, 2],
       [3, 5, 3, 1, 4]], dtype=int32)

In [72]:
np.split(A, 2, axis = 0)

[array([[5, 9, 5, 4, 8],
        [6, 6, 1, 2, 6]], dtype=int32),
 array([[4, 1, 6, 1, 2],
        [3, 5, 3, 1, 4]], dtype=int32)]

In [74]:
np.split(A, [2], axis = 1)

[array([[5, 9],
        [6, 6],
        [4, 1],
        [3, 5]], dtype=int32),
 array([[5, 4, 8],
        [1, 2, 6],
        [6, 1, 2],
        [3, 1, 4]], dtype=int32)]

In [75]:
A 

array([[5, 9, 5, 4, 8],
       [6, 6, 1, 2, 6],
       [4, 1, 6, 1, 2],
       [3, 5, 3, 1, 4]], dtype=int32)

In [77]:
X_input, y_output = np.split(A, [-1], axis = 1)

In [78]:
X_input, y_output

(array([[5, 9, 5, 4],
        [6, 6, 1, 2],
        [4, 1, 6, 1],
        [3, 5, 3, 1]], dtype=int32),
 array([[8],
        [6],
        [2],
        [4]], dtype=int32))

In [80]:
X.reshape(3,2,-1)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [82]:
big_arr = np.array(range(10**6+1))

In [83]:
np.sqrt(X)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162])

In [85]:
np.cos(X)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396])

In [86]:
np.sum(X)

np.int64(78)

In [87]:
%timeit np.sum(big_arr)

733 μs ± 47 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [88]:
%timeit sum(big_arr)

89.5 ms ± 8.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [89]:
%timeit sum(range(10**6+1))

73.2 ms ± 18.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [90]:
A

array([[5, 9, 5, 4, 8],
       [6, 6, 1, 2, 6],
       [4, 1, 6, 1, 2],
       [3, 5, 3, 1, 4]], dtype=int32)

In [91]:
A>4

array([[ True,  True,  True, False,  True],
       [ True,  True, False, False,  True],
       [False, False,  True, False, False],
       [False,  True, False, False, False]])

In [92]:
A[A>4]

array([5, 9, 5, 8, 6, 6, 6, 6, 5], dtype=int32)

In [93]:
A 

array([[5, 9, 5, 4, 8],
       [6, 6, 1, 2, 6],
       [4, 1, 6, 1, 2],
       [3, 5, 3, 1, 4]], dtype=int32)

In [95]:
A 

array([[5, 9, 5, 4, 8],
       [6, 6, 1, 2, 6],
       [4, 1, 6, 1, 2],
       [3, 5, 3, 1, 4]], dtype=int32)

In [94]:
np.sort(A)

array([[4, 5, 5, 8, 9],
       [1, 2, 6, 6, 6],
       [1, 1, 2, 4, 6],
       [1, 3, 3, 4, 5]], dtype=int32)

In [98]:
np.sort(A, axis= 1)

array([[4, 5, 5, 8, 9],
       [1, 2, 6, 6, 6],
       [1, 1, 2, 4, 6],
       [1, 3, 3, 4, 5]], dtype=int32)

In [96]:
np.sort(A, axis= 0)

array([[3, 1, 1, 1, 2],
       [4, 5, 3, 1, 4],
       [5, 6, 5, 2, 6],
       [6, 9, 6, 4, 8]], dtype=int32)

In [99]:
np.sort(A, axis= None)

array([1, 1, 1, 1, 2, 2, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 8, 9],
      dtype=int32)

In [101]:
arr = np.array([2,3,5,3,4,6,3])
np.sort(arr)

array([2, 3, 3, 3, 4, 5, 6])

In [103]:
arr[np.argsort(arr)]

array([2, 3, 3, 3, 4, 5, 6])